/*
 * MyFavorite.java
 *
 * Created on __DATE__, __TIME__
 */

package gerenxinxi;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import view.MyJpanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.table.DefaultTableModel;

import MyRend.MyRender11;
import model.ModelFactory;

import javax.swing.GroupLayout;

/**
 *
 * @author  __USER__
 */
public class MyFavorite extends javax.swing.JFrame {
	static DefaultTableModel model =new DefaultTableModel() ;
	public static void showTable() {
		model.setRowCount( 0 );
		model.setColumnIdentifiers(new Object[]{"商店", "取消收藏"});
		jTable1.getColumnModel().getColumn(0).setPreferredWidth(165);
		jTable1.getColumnModel().getColumn(1).setPreferredWidth(165);
  		ModelFactory m=new ModelFactory();
  		m.viewshoucang();
  		String[] shopn;
  		String one = null;
  		shopn=m.shopname;
  		for(int b=0;b<shopn.length;) {
  			one=shopn[b];
  			b++;
  			model.addRow(new Object[]{one,null}); 
  		}
		jTable1.getColumnModel().getColumn(1).setCellEditor(new MyRender11(jTable1));
		jTable1.getColumnModel().getColumn(1).setCellRenderer(new MyRender11(jTable1));
	}
	/** Creates new form MyFavorite */
	public MyFavorite() {
		initComponents();
		showTable();
		this.setTitle("我的收藏");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new MyJpanel("lib//image//04.png");
		jTable1 = new JTable(model);
		jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane1= new JScrollPane(jTable1);
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
					.addGap(94)
					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(98, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
					.addGap(38)
					.addComponent(jButton2)
					.addGap(49))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MyFavorite().setVisible(true);
			}
		});
	}
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private static javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}