/*
 * foodtable2.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


import MyRend.*;
import model.ModelFactory;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author  __USER__
 */
public class foodtable2 extends javax.swing.JFrame {
	ModelFactory m=new ModelFactory();
	DefaultTableModel model =new DefaultTableModel() ;
	DefaultTableModel model1 =new DefaultTableModel() ;
	public void showTable() {//吃
		model.setRowCount( 0 );
		model.setColumnIdentifiers(new Object[]{"食品id", "食品名称","食品价格",""});
		jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
		jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
		jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
		jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
  		m.vieweatfood(MyRender4.shopn);
  		int[] id;
  		String[] foodn;
  		String[] price;
  		String[] youhui;
  		int one;
  		String two=null;
  		String three=null;
  		String four=null;
  		double five;
  		id=m.id;
  		foodn=m.foodn;
  		price=m.price;
  		youhui=m.youhui;
  		for(int b=0;b<id.length;) {
  			one=id[b];
  			two=foodn[b];
  			three=price[b];
  			four=youhui[b];
  			five=Double.parseDouble(three)*Double.parseDouble(four);
  			b++;
  			model.addRow(new Object[]{one,two,five,null}); 
  		}
		jTable1.getColumnModel().getColumn(3).setCellEditor(new MyRender5(jTable1));
		jTable1.getColumnModel().getColumn(3).setCellRenderer(new MyRender5(jTable1));
	}

	public void showTable1() {//喝
		model1.setRowCount( 0 );
		model1.setColumnIdentifiers(new Object[]{"食品id", "食品名称","食品价格",""});
		jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
		jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
		jTable2.getColumnModel().getColumn(2).setPreferredWidth(80);
		jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
  		m.viewdrinkfood(MyRender4.shopn);
  		int[] id;
  		String[] foodn;
  		String[] price;
  		String[] youhui;
  		int one;
  		String two=null;
  		String three=null;
  		String four=null;
  		double five;
  		id=m.id;
  		foodn=m.foodn;
  		price=m.price;
  		youhui=m.youhui;
  		for(int b=0;b<id.length;) {
  			one=id[b];
  			two=foodn[b];
  			three=price[b];
  			four=youhui[b];
  			five=Double.parseDouble(three)*Double.parseDouble(four);
  			b++;
  			model1.addRow(new Object[]{one,two,five,null}); 
  		}
		jTable2.getColumnModel().getColumn(3).setCellEditor(new MyRender5(jTable2));
		jTable2.getColumnModel().getColumn(3).setCellRenderer(new MyRender5(jTable2));
	}

	/** Creates new form foodtable2 */
	public foodtable2() {
		initComponents();
		showTable();
		showTable1();
		this.setTitle("商品列表");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1= new MyJpanel("lib//image//1.png");
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		
		jTable1 = new JTable(model);
		jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane1= new JScrollPane(jTable1);
		
		jPanel3 = new javax.swing.JPanel();
		
		jTable2 = new JTable(model1);
		jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane2= new JScrollPane(jTable2);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u8fd4\u56de");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText(MyRender4.shopn);

		jTabbedPane1.setFont(new java.awt.Font("方正水云简体_中", 0, 14));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("\u7f8e\u98df", jPanel2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE));

		jTabbedPane1.addTab("\u996e\u54c1", jPanel3);
		
		JButton button = new JButton("\u5237\u65B0");
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {//刷新
				showTable();
				showTable1();
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
									.addComponent(jLabel1)
									.addGap(31))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(18)
									.addComponent(button, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
									.addContainerGap())))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton1)
						.addComponent(jLabel1)
						.addComponent(button))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new foodtable2().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
}