/*
 * foodtable.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import MyRend.*;
import model.ModelFactory;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author  __USER__
 */
public class foodtable extends javax.swing.JFrame {
	ModelFactory m=new ModelFactory();
	DefaultTableModel model =new DefaultTableModel() ;
	DefaultTableModel model1 =new DefaultTableModel() ;
	public void showTable() {//吃
		model.setRowCount( 0 );
		model.setColumnIdentifiers(new Object[]{"食品id", "食品名称","食品价格",""});
		jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
		jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
		jTable2.getColumnModel().getColumn(2).setPreferredWidth(80);
		jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
  		m.vieweatfood(MyRender.shopn);
  		int[] id;
  		String[] foodn;
  		String[] price;
  		String[] youhui;
  		int one;
  		String two=null;
  		String three=null;
  		String four=null;
  		double five;
  		id=m.id;
  		foodn=m.foodn;
  		price=m.price;
  		youhui=m.youhui;
  		for(int b=0;b<id.length;) {
  			one=id[b];
  			two=foodn[b];
  			three=price[b];
  			four=youhui[b];
  			five=Double.parseDouble(three)*Double.parseDouble(four);
  			b++;
  			model.addRow(new Object[]{one,two,five,null}); 
  		}
		jTable2.getColumnModel().getColumn(3).setCellEditor(new MyRender1(jTable2));
		jTable2.getColumnModel().getColumn(3).setCellRenderer(new MyRender1(jTable2));
	}

	public void showTable1() {//喝
		model1.setRowCount( 0 );
		model1.setColumnIdentifiers(new Object[]{"食品id", "食品名称","食品价格",""});
		jTable3.getColumnModel().getColumn(0).setPreferredWidth(80);
		jTable3.getColumnModel().getColumn(1).setPreferredWidth(100);
		jTable3.getColumnModel().getColumn(2).setPreferredWidth(80);
		jTable3.getColumnModel().getColumn(3).setPreferredWidth(100);
  		m.viewdrinkfood(MyRender.shopn);
  		int[] id;
  		String[] foodn;
  		String[] price;
  		String[] youhui;
  		int one;
  		String two=null;
  		String three=null;
  		String four=null;
  		double five;
  		id=m.id;
  		foodn=m.foodn;
  		price=m.price;
  		youhui=m.youhui;
  		for(int b=0;b<id.length;) {
  			one=id[b];
  			two=foodn[b];
  			three=price[b];
  			four=youhui[b];
  			five=Double.parseDouble(three)*Double.parseDouble(four);
  			b++;
  			model1.addRow(new Object[]{one,two,five,null}); 
  		}
		jTable3.getColumnModel().getColumn(3).setCellEditor(new MyRender1(jTable3));
		jTable3.getColumnModel().getColumn(3).setCellRenderer(new MyRender1(jTable3));
	}

	/** Creates new form foodtable */
	public foodtable() {
		initComponents();
		showTable();
		showTable1();
		this.setTitle("商品列表");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel1 = new MyJpanel("lib//image//4.png");
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		
		jTable2 = new JTable(model);
		jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane2= new JScrollPane(jTable2);
		
		jPanel3 = new javax.swing.JPanel();
		
		jTable3 = new JTable(model1);
		jTable3.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane3= new JScrollPane(jTable3);
		
		jLabel1 = new javax.swing.JLabel();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u8fd4\u56de");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u6536\u85cf\u5e97\u94fa");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTabbedPane1.setFont(new java.awt.Font("方正水云简体_中", 0, 14));


		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("\u7f8e\u98df", jPanel2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 352,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("\u996e\u54c1", jPanel3);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText(MyRender.shopn);
		
		button = new JButton();
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				showTable();
				showTable1();
			}
		});
		button.setText("\u5237\u65B0");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
							.addContainerGap(23, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jButton2)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(button, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
							.addComponent(jLabel1)
							.addGap(32))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
							.addComponent(jButton2)
							.addComponent(jButton1)
							.addComponent(button))
						.addComponent(jLabel1))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		ModelFactory.shoucang(MyRender.shopn);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new foodtable().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable3;
	private JButton button;
	// End of variables declaration//GEN-END:variables

}